### ISSUE TITLE
Installer should check for write permissions for .env

### ISSUE THREAD

**Issue by theTrip73** [anomalylabs/installer-module#1]
Just attempted fresh install of 3.0.0-alpha2 tag, and my root directory wouldn't allow creation of .env. After the fail, I corrected it, but I could not proceed and had to completely start over. (I guess this was because the installation partially succeeded before this fault?)

I looked into the installer-module files for the pre-install validation and couldn't find anything on which to try a PR. Maybe this is the wrong module for this issue.

Thanks.

**Comment by RyanThompson** [comment]
Ahhhh ya.. Well we might want to rethink the approach then too: https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Application/Command/CheckDirectoryPermissions.php

**Comment by RyanThompson** [comment]
What did you change your permissions to? I don't want to suggest 777 for your root project directory lol.

**Comment by theTrip73** [comment]
On my dev server, my fix was to go 775 since apache is a member of my ownership group. I can't guarantee the smoothness of that approach on shared production environments, though, obviously.
