### ISSUE TITLE
500 error on /installer/progress after Install form submission.

### ISSUE THREAD

**Issue by theTrip73** [anomalylabs/installer-module#2]
Fresh installation in new /var/www/mywebsite.com directory. I filled out the installation form and received a 500 error on /installer/progress. The only other information I have is the laravel.log contents:

[2015-03-21 03:28:52] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Method Anomaly\Streams\Platform\Image\Image::__toString() must not throw an exception' in /var/www/mywebsite.com/storage/framework/views/twig/cb/c0/c974c802af131fc77ca6beb64008e965adf1462942773f7f30389be5f5cf.php:0
Stack trace:
#0 {main}  
[2015-03-21 03:28:52] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getNamespace() on a non-object' in /var/www/mywebsite.com/vendor/anomaly/streams-platform/src/View/ViewComposer.php:86
Stack trace:
#0 {main}

**Comment by theTrip73** [comment]
I tried another fresh installation. It failed as well, but then I hacked it a bit.

I manually deleted my .env file which allowed me to view the installation form again, but this time, instead of using 'mywebsite' as the Application Reference, I used 'default'. It worked.

This was an error I encountered multiple times while messing around with the 3.0/develop branch. I will update the issue title with a more accurate description.

**Comment by RyanThompson** [comment]
Can you try this once more now that you have the env permissions thing in mind? I do believe (aside from perhaps permissions) this should work fine.

**Comment by theTrip73** [comment]
This actually happened on a fresh install after I knew to adjust for .env, so that was not an issue with this bug. To me, it appears to be the same (or a very similar) issue that we talked about on Twitter. I looked but couldn't find any explicit references to 'default', so I'm not sure why installation works with it as the application reference while using 'mywebsite' doesn't/didn't work.

I will try again tonight if I haven't heard back before then.

**Comment by theTrip73** [comment]
This is confirmed. Fresh install failed with "mywebsite" as application reference. Another fresh install worked with "default" as application reference.

**Comment by RyanThompson** [comment]
Can you check the permissions of your assets / storage folder again. Do 777 in there on the mywebsite dirs and rerun the same installation. 

I was running into an issue where the directory created, was not writable.. which was odd.

**Comment by theTrip73** [comment]
That might be a different issue, though, right? Permissions wouldn't explain the errors in the first comment, would they?

**Comment by theTrip73** [comment]
You are correct, though. The public/assets/mywebsite directory is "dr----x--t" (611? I feel like a newbie for not knowing what the 't' means.), and the public/assets/default directory is 775.

**Comment by RyanThompson** [comment]
Shit I don' know what the dr----x--t means at all lol. I always go off the number. 611 is dumb though.. should not be like that. Looking into this, thanks!

**Comment by theTrip73** [comment]
Second confirmation -- chmod to 775 on the mywebsite directory allowed installation to work after a stalled attempt.

**Comment by RyanThompson** [comment]
Can you try a fresh installation now? This should be your latest commit: https://github.com/anomalylabs/streams-platform/commit/5f6c556c6fc7908b258032c949da0652fcf5fb22

Perhaps `composer clear-cache` for safety sake.

**Comment by RyanThompson** [comment]
Looks like I've got a few other things to do real quick to finish this.

**Comment by RyanThompson** [comment]
This should be ready to go - pull and confirm if you would please.

**Comment by theTrip73** [comment]
Sorry it's taken so long to get to this. I hope to have some time to spend on this tonight.

**Comment by RyanThompson** [comment]
All good!

**Comment by theTrip73** [comment]
Tried it last night and got a 500 error related to an invalid view name for trigbridge.

Tried it tonight with all of today's package updates and got the same error.

It looks like it's trying to load the content of the view/template instead of its name. It's a View Not Found error from twigbridge, but the name is like 500+ lines of CSS.

**Comment by RyanThompson** [comment]
Reloading will remedy this - not sure why it's happening though..

**Comment by theTrip73** [comment]
Very strange that that fixes it. Maybe it has something to do with the redirect response in the form handler.

    $form->setResponse(redirect('installer/install'));

Something about the refresh makes it a little different, obviously. I can't imagine what it could be. Have you seen this error (or heard of anyone else running into it)?

**Comment by RyanThompson** [comment]
Ive not but havent looked too terribly hard. It has to do with compiling AND using twig on the compiled file for the FIRST time only.. weird.
